Esm conversion
bbc/bigscreen-player pull request #241
Opened 2021-09-20 13:02 UTC by jlks

📺 What

[Enter a brief description of what this pull request does]

[Add the jira ticket and/or the ADR to this PR]
> Tickets: IPLAYERTVV1-XXXX

🛠 How

[How does this PR perform the features described in What, keep technical detail brief and/or high level - more detail can be requested in comments]

✅ Testing [Semi-optional]
[MANDATORY for contributions being tested and released by the contributing team]

[Test Guidelines](https://github.com/bbc/bigscreen-player/wiki/Areas-Impacted)

| Test engineer sign off | :x: |
| ---- | ---- |

[How will this change be tested?]

👀  See [optional]

[Describe or add screenshots of any User facing changes]
[If the PR has User Facing changes - this section is mandatory]

♿  Accessibility [optional]

[Any accessibility features or considerations that this PR addresses should be listed here]

 ✅ Acceptance criteria [Optional]

[MANDATORY for cross-team reviews]
* [X] [Add the acceptance criteria or some from the linked ticket number]
* [ ] [Mark correctly if it is covered in this PR or not]

2021-10-05 08:43 UTC, matt-stephenson approved these changes

2021-10-06 07:57 UTC, domjacks requested changes
🚀

2021-10-06 08:29 UTC, domjacks commented on index.html
> +<!DOCTYPE html>
Ah I see 👍

2021-10-06 08:35 UTC, jlks commented on .eslintignore
>  buildExternal.js
Done!

2021-10-06 08:36 UTC, domjacks approved these changes

2021-10-06 09:41 UTC, merged